---
# tasks file for gissues

- name: "Manage Gitlab Issues for {{ gissues_project_path }}"
  ansible.builtin.include_tasks:
    file: manage-issues.yml
  loop: "{{ gissues_issue_list }}"
  loop_control:
    loop_var: issue
    label: "{{ issue.title }}"

