---
# tasks file for gissues
#
# Present search closed, found = not create new opened
# Present search closed, not found = create new opened
# Present search opened, found = not create new opened
# Present search opened, not found = create new opened
# Absent search closed, found = delete closed
# Absent search closed, not found = no action
# Absent search opened, found = delete opened
# Absent search opened, not found = no action


# Issue should exist or it should not
- name: Set Fact About Issue State
  ansible.builtin.set_fact:
    gissue_exists: "{{ issue.state | default('present') != 'absent' }}"

# Template takes precedence over description
- name: Set Fact About Issue Description
  ansible.builtin.set_fact:
    gissue_template: "{{ lookup('template', 'issue.template') }}"
  when:
    - issue.template is defined
    - issue.template != ''

- name: Manage Closed Gitlab Issues
  community.general.gitlab_issue:
    api_job_token: "{{ gissues_api_job_token | default(omit) }}"
    api_oauth_token: "{{ gissues_api_oauth_token | default(omit) }}"
    api_username: "{{ gissues_api_username | default(omit) }}"
    api_password: "{{ gissues_api_password | default(omit) }}"
    api_url: "{{ gissues_api_url }}"
    api_token: "{{ gissues_api_token }}"
    project: "{{ gissues_project }}"
    title: "{{ issue.title }}"
    description: "{{ gissue_template | default(issue.description) | default(omit) }}"
    state: "{{ issue.state | default(omit) }}"
    labels: "{{ issue.labels | default(omit) }}"
    assignee_ids: "{{ issue.assignee_ids | default(omit) }}"
    milestone_search: "{{ issue.milestone_search | default(omit) }}"
    milestone_group_id: "{{ issue.milestone_group_id | default(omit) }}"
    validate_certs: "{{ gissues_validate_certs | default(omit) }}"
    state_filter: "{{ issue.state_filter }}"
    issue_type: "{{ issue.issue_type | default(omit) }}"
    ca_path: "{{ issue.ca_path | default(omit) }}"
  when: gissue_exists
  register: issue_result

- name: Set Issue Facts
  ansible.builtin.set_fact:
    gissue_current_id: "{{ issue_result.issue.id }}"
    gissue_current_iid: "{{ issue_result.issue.iid }}"
    gissue_current_project_id: "{{ issue_result.issue.project_id }}"
    gissue_current_state: "{{ issue_result.issue.state }}"
    gissue_current_url: "{{ gissues_api_url }}/api/v4/projects/{{ issue_result.issue.project_id }}/issues/{{ issue_result.issue.iid }}"
  when: gissue_exists

- name: Assign Issue Epic/Parent
  ansible.builtin.uri:
    url: "{{ gissue_current_url }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gissues_api_token }}"
    body_format: json
    body:
      epic_id: "{{ issue.epic_id | default(0) | int }}"
    status_code: 200
    validate_certs: "{{ gissues_validate_certs }}"
  when: gissue_exists

- name: Close Gitlab Issue
  ansible.builtin.uri:
    url: "{{ gissue_current_url }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gissues_api_token }}"
    body_format: json
    body:
      state_event: close
    status_code: 200
    validate_certs: "{{ gissues_validate_certs }}"
  when:
    - gissue_exists
    - issue.closed | default(false)

- name: Reopen Gitlab Issue
  ansible.builtin.uri:
    url: "{{ gissue_current_url }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gissues_api_token }}"
    body_format: json
    body:
      state_event: reopen
    status_code: 200
    validate_certs: "{{ gissues_validate_certs }}"
  when:
    - gissue_exists
    - issue.state_filter == 'closed'
    - gissue_current_state == 'closed'

# State 3: Delete issue whether opened or closed
- name: Delete Issue
  community.general.gitlab_issue:
    api_url: "{{ gissues_api_url }}"
    api_token: "{{ gissues_api_token }}"
    project: "{{ gissues_project }}"
    title: "{{ issue.title }}"
    state: "{{ issue.state }}"
    state_filter: "{{ item }}"
    validate_certs: "{{ gissues_validate_certs }}"
  loop:
    - opened
    - closed
  when: not gissue_exists
